indoctrinatr/config/routes.rb
Rails.application.routes.draw do
  resources :magics

  root 'magics#index'

     resources :magics

end

indoctrinatr/app/models/magic.rb
class Magic < ActiveRecord::Base
end

indoctrinatr/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

indoctrinatr/app/controllers/magics_controller.rb
class MagicsController < ApplicationController
  before_action :set_magic, only: [:show, :edit, :update, :destroy]

  # GET /magics
  # GET /magics.json
  def index
    @magics = Magic.all
  end

  # GET /magics/1
  # GET /magics/1.json
  def show
  end

  # GET /magics/new
  def new
    @magic = Magic.new
  end

  # GET /magics/1/edit
  def edit
  end

  # POST /magics
  # POST /magics.json
  def create
    @magic = Magic.new(magic_params)

    respond_to do |format|
      if @magic.save
        format.html { redirect_to @magic, notice: 'Magic was successfully created.' }
        format.json { render :show, status: :created, location: @magic }
      else
        format.html { render :new }
        format.json { render json: @magic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /magics/1
  # PATCH/PUT /magics/1.json
  def update
    respond_to do |format|
      if @magic.update(magic_params)
        format.html { redirect_to @magic, notice: 'Magic was successfully updated.' }
        format.json { render :show, status: :ok, location: @magic }
      else
        format.html { render :edit }
        format.json { render json: @magic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magics/1
  # DELETE /magics/1.json
  def destroy
    @magic.destroy
    respond_to do |format|
      format.html { redirect_to magics_url, notice: 'Magic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_magic
      @magic = Magic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def magic_params
      params.require(:magic).permit(:spell)
    end
end

indoctrinatr/app/helpers/application_helper.rb
module ApplicationHelper
end

indoctrinatr/app/helpers/magics_helper.rb
module MagicsHelper
end

indoctrinatr/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

indoctrinatr/app/views/magics/_form.html.erb
<%= form_for(@magic) do |f| %>
  <% if @magic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@magic.errors.count, "error") %> prohibited this magic from being saved:</h2>

      <ul>
      <% @magic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spell %><br>
    <%= f.text_field :spell %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

indoctrinatr/app/views/magics/edit.html.erb
<h1>Editing Magic</h1>

<%= render 'form' %>

<%= link_to 'Show', @magic %> |
<%= link_to 'Back', magics_path %>

indoctrinatr/app/views/magics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Magics</h1>

<table>
  <thead>
    <tr>
      <th>Spell</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magics.each do |magic| %>
      <tr>
        <td><%= magic.spell %></td>
        <td><%= link_to 'Show', magic %></td>
        <td><%= link_to 'Edit', edit_magic_path(magic) %></td>
        <td><%= link_to 'Destroy', magic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Magic', new_magic_path %>

indoctrinatr/app/views/magics/new.html.erb
<h1>New Magic</h1>

<%= render 'form' %>

<%= link_to 'Back', magics_path %>

indoctrinatr/app/views/magics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Spell:</strong>
  <%= @magic.spell %>
</p>

<%= link_to 'Edit', edit_magic_path(@magic) %> |
<%= link_to 'Back', magics_path %>